### ISSUE TITLE
Cant download plugin on 2 i2p routers.

### ISSUE THREAD

**Issue by egeneralov** [miximka/I2PMonitor#1]
# Links dead.

http://plugins.i2p/files/I2PControl.xpi2p 
http://itoopie.i2p/files/I2PControl.xpi2p

Please, contact me with PGP mail: 

> eduard@generalov.net

I have live host in i2p, server will work for **3+** years.

**Comment by miximka** [comment]
Hi, thanks for the hint with dead links!! I just updated the readme and provided a [link](http://i2pmonitor.de/I2PPlugins/I2PControl/0.11-b0/I2PControl.xpi2p) for direct plugin download. Download and install the plugin directly.
